import { Component } from '@angular/core';
import { HeaderComponent } from '../../common/example-header/example-header';
import {
  PdkTypographyDirective,
  PdkFormComponent,
  PdkFormFieldComponent,
  PdkInputComponent,
  PdkInputDirective,
  PdkTextInputDirective,
  PdkButtonComponent,
  PdkButtonDirective,
  PdkMarginDirective
} from '@cpp/pdk';
import { ExampleComponent } from '../../common/example/example.component';
import { FormsModule } from '@angular/forms';
import {
  CodeComponent,
  PropsListComponent,
  PropsListItemComponent
} from '../../common/props-list/props-list';

const html = `
<form novalidate pdk-form (validSubmit)="handleSubmit($event)">
  <pdk-form-field
    label="National insurance number"
    labelType="medium"
    hintText="It’s on your National Insurance card, benefit letter, payslip or P60. For example, QQ123456C."
    [errorMessages]="errorMessages"
  >
    <input
      type="text"
      ngModel
      name="nin"
      pdk-input
      pdk-text-input
      required
      minlength="9"
    />
  </pdk-form-field>
  <button pdk-button type="submit">Save</button>
</form>
`;

const ts = `
class ExampleComponent {
  errorMessages = [
    {
      rule: 'required',
      message: 'Provide your national insurance information'
    },
    {
      rule: 'minlength',
      message: 'National insurance number too short'
    }
  ]

  handleSubmit(e) {
    alert(\`Your form was submitted with \${JSON.stringify(e)}\`);
  }
}
`;
@Component({
  selector: 'docs-form-field',
  template: `
    <docs-example-header origin="GOV.UK">
      <span pdk-typography="caption-xlarge">Components</span>
      <h1 pdk-typography="heading-xlarge">Forms</h1>
    </docs-example-header>
    <p pdk-typography="body">
      Forms within the Platform Development Kit expose a simple api where the components inherently
      take care of accessibility and displaying error messages.
    </p>

    <!-- Example -->

    <h2 pdk-typography="heading-large">Example</h2>

    <docs-example [html]="html" [typescript]="ts">
      <form novalidate pdk-form (validSubmit)="handleSubmit($event)">
        <pdk-form-field
          label="National insurance number"
          labelType="medium"
          hintText="It’s on your National Insurance card, benefit letter, payslip or P60. For example, QQ123456C."
          [errorMessages]="errorMessages"
        >
          <input type="text" ngModel name="nin" pdk-input pdk-text-input required minlength="9" />
        </pdk-form-field>
        <button pdk-button type="submit" pdk-margin="0">Save</button>
      </form>
    </docs-example>

    <!-- Api -->

    <h2 pdk-typography="heading-large">Api</h2>
    <p pdk-typography="body">
      Add <code docs-code>PdkForm</code> to your list of ngModule/standalone component imports.
    </p>

    <h3 pdk-typography="heading-medium">[pdk-form]</h3>
    <p pdk-typography="body">
      This directive should be applied to any containing form that uses
      <code docs-code>pdk-form-field</code>.
    </p>
    <docs-props-list [propWidth]="160">
      <docs-props-list-item
        name="errorFormat"
        type="enum: 'default' | 'extended'"
        defaultValue="default"
      >
        When <code docs-code>extended</code>, prepends the label of a form control to its error
        message before invoking the <code docs-code>errors</code> expression.
      </docs-props-list-item>
      <docs-props-list-item name="errors" type="expression">
        An event callback triggered when the form is submitted, where
        <code docs-code>$event</code> emits <code docs-code>null</code> when the form is valid, and
        is a collection of <code docs-code>ValidationError</code> when invalid.
      </docs-props-list-item>
      <docs-props-list-item name="validSubmit" type="expression">
        An event callback triggered when the form is submitted without errors, where
        <code docs-code>$event</code> is the form value.
      </docs-props-list-item>
    </docs-props-list>

    <h3 pdk-typography="heading-medium">pdk-form-field</h3>
    <p pdk-typography="body">
      This component should directly contain exactly one input that functions as a
      <code docs-code>ControlValueAcessor</code> and <code docs-code>FormFieldControl</code>. In
      more complex forms, a <code docs-code>pdk-form-field</code> can be nested inside of another.
    </p>

    <docs-props-list [propWidth]="160">
      <docs-props-list-item name="ng-content" type="node">
        The content of the form field. This child must function as a
        <code docs-code>FormFieldControl</code> provider.
      </docs-props-list-item>
      <docs-props-list-item name="errors" type="object">
        Optionally, the validation errors can be provided and will supercede those generated by the
        nested <code docs-code>FormFieldControl</code>. This can be useful for annotating
        asynchronous errors raised by the server.
      </docs-props-list-item>
      <docs-props-list-item name="errorMessages" type="array" defaultValue="[]">
        A list of error configuration objects, where: <br />
        1. <code docs-code>rule</code> identifies the type of error found on an
        <code docs-code>ngControl</code> <br />
        2. <code docs-code>message</code> is an error message string or a function that returns an
        error message.
      </docs-props-list-item>
      <docs-props-list-item name="hint" type="boolean" defaultValue="false">
        When <code docs-code>true</code>, displays (where applicable) the default hint belonging to
        the nested <code docs-code>FormFieldControl</code>.
      </docs-props-list-item>
      <docs-props-list-item name="hintText" type="string">
        A description of the form field.
      </docs-props-list-item>
      <docs-props-list-item name="label" type="string">
        The label text for the form field.
      </docs-props-list-item>
      <docs-props-list-item
        name="labelType"
        type="enum: default | small | medium | large | xlarge | none"
        defaultValue="default"
      >
        The type of styling for the label text. When <code docs-code>none</code> is used, the label
        is only available to screen readers.
      </docs-props-list-item>
      <docs-props-list-item name="labelForErrorSummary" type="string">
        An optional second label to be used instead the regular label when displaying a a validation
        error in the error summary.
      </docs-props-list-item>
    </docs-props-list>
  `,
  imports: [
    HeaderComponent,
    PdkTypographyDirective,
    ExampleComponent,
    FormsModule,
    PdkFormComponent,
    PdkFormFieldComponent,
    PdkInputComponent,
    PdkInputDirective,
    PdkTextInputDirective,
    PdkButtonComponent,
    PdkButtonDirective,
    PdkMarginDirective,
    CodeComponent,
    PropsListComponent,
    PropsListItemComponent
  ]
})
export class FormsComponent {
  html = html;
  ts = ts;
  errorMessages = [
    {
      rule: 'required',
      message: 'Provide your national insurance information'
    },
    {
      rule: 'minlength',
      message: 'National insurance number too short'
    }
  ];
  handleSubmit(e) {
    alert(`Your form was submitted with ${JSON.stringify(e)}`);
  }
}
